# Generated by Django 5.1.6 on 2025-02-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_plate_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='piece_availability',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pieces_used',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
